### ISSUE TITLE
TPA: Reflection - Invalid return value of GetTypeKind()

### ISSUE THREAD

**Issue by michudzik** [mpostol/TP#80]
Steps to reproduce:

1. Create a class which consists of other classes (Ex. Book has an Author(custom defined class) and Release Date(DateTime)

2. Load assembly

3. Check TypeKind in TypeMetadata - Book will be seen correctly, as a class, however Author and ReleaseDate are indicated as enums

**Comment by mpostol** [comment]
Let me know what project it is related to?  Is it TP or TPA. I will appreciate the direct link to the class or just fork, correct and pr.

**Comment by michudzik** [comment]
The problem is related to the TP project.

Whole programme is available at: 
https://serce.ics.p.lodz.pl/svn/labs/tp/2018l_mp_pt12/215145/tags/project_5.0 
which You have access to via TUL servers. 
Sample dll is included in the UnitTestProject/CustomData/dll/ directory.

**Comment by mpostol** [comment]
Thanks, but adding internal (private) links to open repository is not good practice - the people should know what we are talking about.
Anyway, I will address this at due time.

**Comment by michudzik** [comment]
Thanks for the feedback. I will create public repository and replace those links asap.

**Comment by mpostol** [comment]
The problem relates to:
TypeMetadata.GetTypeKind(System.Type)
and TPA solution.

**Comment by Anakinud** [comment]
Problem isn't in `TypeMetadata.GetTypeKind`. Problem is in `TypeMetadata.TypeMetdata(string, string)`, and `TypeMetadata(string, string, IEnumerable<TypeMetadata>)` more specifically in c#'s initialization variables by default values. When there are used enums, which are value types, they are automatically initialized with represantation of 0 in this case this is `TypeMetadata.TypeKind.EnumType`, (More info about enum defaults in this link: https://stackoverflow.com/a/4967673/9217084) This problem is only when we reflect types used as fields, parameters, return types and so on.

Solutions which comes to my mind:
1. Change enum fields to nullable enums. When we don't want to have information about something what was described by this enum we "skip" this.
2. Add `TypeMetadata.TypeKind.Nohing` (example name) which will represant 0

P.S. Similar problem with other enums e.g. StaticEnum, SealedEnum (and similar solution).
